name: C/C++ CI

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libboost-dev doctest-dev
    - name: make build dir
      run: mkdir build
    - name: configure
      run: cmake -G Ninja -DRX_TEST=ON -S . -B build
    - name: build
      run: ninja -C build
    - name: run tests
      run: build/rx-ranges-test
