name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request: []

jobs:
  GCC9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: (sudo apt-get update && sudo apt-get install libboost-date-time-dev libbenchmark-dev doctest-dev ninja-build cmake build-essential g++-9)
    - name: make build dir
      run: mkdir build
    - name: configure
      run: (cd build && cmake .. -G Ninja -DRX_TEST=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/g++-9)
    - name: build
      run: ninja -C build
    - name: run tests
      run: build/rx-ranges-test && build/rx-calendar
  Clang8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: (sudo apt-get update && sudo apt-get install libbenchmark-dev libboost-date-time-dev doctest-dev ninja-build cmake build-essential clang-8)
    - name: make build dir
      run: mkdir build
    - name: configure
      run: (cd build && cmake .. -G Ninja -DRX_TEST=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8)
    - name: build
      run: ninja -C build
    - name: run tests
      run: build/rx-ranges-test && build/rx-calendar
  Clang8-Libcxx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: (sudo apt-get update && sudo apt-get install libbenchmark-dev libboost-date-time-dev doctest-dev ninja-build cmake build-essential clang-8 libc++-8-dev libc++abi-8-dev)
    - name: make build dir
      run: mkdir build
    - name: configure
      run: (cd build && cmake .. -G Ninja -DRX_TEST=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++ -lm -lc -lgcc_s -lgcc")
    - name: build
      run: ninja -C build
    - name: run tests
      run: build/rx-ranges-test && build/rx-calendar
  GCC9-Benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: (sudo apt-get update && sudo apt-get install libboost-date-time-dev libbenchmark-dev doctest-dev ninja-build cmake build-essential g++-9)
    - name: make build dir
      run: mkdir build
    - name: configure
      run: (cd build && cmake .. -G Ninja -DRX_TEST=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++-9)
    - name: build
      run: ninja -C build
    - name: run tests
      run: build/rx-ranges-test && build/rx-benchmark
  Clang8-libcxx-Benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: (sudo apt-get update && sudo apt-get install libbenchmark-dev libboost-date-time-dev doctest-dev ninja-build cmake build-essential clang-8 libc++-8-dev libc++abi-8-dev)
    - name: make build dir
      run: mkdir build
    - name: configure
      run: (cd build && cmake .. -G Ninja -DRX_TEST=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++ -lm -lc -lgcc_s -lgcc")
    - name: build
      run: ninja -C build
    - name: run tests
      run: build/rx-ranges-test && build/rx-benchmark